version: '3.7'
services:
  db:
    container_name: mongodb
    image: gabrielgdsg/myrepo:mongodb
#    image: mongo:latest
#    env_file:
#      - develop_docker.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
#      MONGO_HOST_DATA: D:/mongodb_volume
    ports:
      - 27017:27017
    volumes:
      - mongodb-volume:/data/db
volumes:
    mongodb-volume:

networks:
      default:
        external:
          name: my-net

